# language: node_js
# node_js:
#   - "node"
# cache: yarn

# before_install:
#   - curl -o- -L https://yarnpkg.com/install.sh | bash
#   - export PATH="$HOME/.yarn/bin:$PATH"

# script:
#   - yarn build && yarn test

# notifications:
#   webhooks: https://code.facebook.com/travis/webhook/
